# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

env:
  - TOXENV=flake8
  - TOXENV=pep257
   #- TOXENV=docs
  - TOXENV=manifest


before_install:
  - pip install codecov

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox codecov

# command to run tests, e.g. python setup.py test
script:
  - make test-all
